name = "prisma-d1-example"
main = "src/index.ts"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "prisma-demo-db"
database_id = "7c57d4f2-a5b3-4024-8899-74f9e429ff59"
